spring.application.name=example01
spring.datasource.url=jdbc:mysql://localhost:3306/example01
spring.datasource.username=root
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
    springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs